version: '3.8'
services:
  web:
    build: .
    image: acrobits-websvc
    container_name: acrobits_websvc
    command: ["-c", "/config/acrobits-websvc.json"]
    ports:
      - 8080:8080
    volumes:
      - ./config/:/config/:ro
