version: '3.8'
services:
  web:
    build: ./app/
    image: 'acrobits-websvc'
    container_name: acrobits_websvc
    ports:
      - '8000:8000'
    volumes:
      - './certs/:/usr/src/certs/:ro'
    env_file:
      - './config/acrobits-websvc.env'
